name: CI

on:
  push:

jobs:
  ci:
    name: Run Continuous Integration Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run TypeScript type checking
      run: npx tsc --noEmit 

    - name: Run eslint
      run: npm run lint  

    - name: Run Prettier
      run: npm run prettier 

    - name: Run tests
      run: npm test 

  check-version:
    name: Check Package Version
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current version from package.json
      id: get_version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "Current version is: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Get list of existing Git tags
      run: |
        git fetch --tags
        git tag

    - name: Check if version exists in tags
      run: |
        if git tag --list | grep -q "${{ steps.get_version.outputs.version }}"; then
          echo "Error: Version ${{ steps.get_version.outputs.version }} already exists as a tag."
          exit 1
        fi
